/**
 * STEP 23 / C-23.2 — 信号→订单→成交→PnL 闭环编排：结构化错误（FAIL FAST，稳定 code）。
 *
 * 编排层在非法输入 / 编排不变量破坏下抛 SignalToPnlError（稳定 code），
 * 绝不静默 clamp / 回退 / 伪造。code 供程序化处理（非自由文本）。
 */

/** C-23.2 信号→PnL 编排错误（code 稳定）。 */
export class SignalToPnlError extends Error {
  /** 稳定错误码（非自由文本）。 */
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "SignalToPnlError";
    this.code = code;
  }
}

/** 稳定错误码集合（编排 / 输入 / 来源 / 序列化）。 */
export const SIGNAL_TO_PNL_ERROR_CODES = {
  // 输入边界
  INPUT_INVALID: "SIGNAL_TO_PNL_INPUT_INVALID",
  INPUT_ACCOUNT_ASOF_INVALID: "SIGNAL_TO_PNL_ACCOUNT_ASOF_INVALID",
  INPUT_CALENDAR_INVALID: "SIGNAL_TO_PNL_CALENDAR_INVALID",
  INPUT_CALENDAR_EMPTY: "SIGNAL_TO_PNL_CALENDAR_EMPTY",
  INPUT_RUN_ID_INVALID: "SIGNAL_TO_PNL_RUN_ID_INVALID",
  INPUT_ACCOUNT_ID_INVALID: "SIGNAL_TO_PNL_ACCOUNT_ID_INVALID",
  INPUT_PRICE_SOURCE_MISSING: "SIGNAL_TO_PNL_PRICE_SOURCE_MISSING",

  // 来源校验
  SOURCE_KIND_INVALID: "SIGNAL_TO_PNL_SOURCE_KIND_INVALID",
  SOURCE_FINGERPRINT_MISMATCH: "SIGNAL_TO_PNL_SOURCE_FINGERPRINT_MISMATCH",
  SOURCE_DECISION_POINT_INVALID: "SIGNAL_TO_PNL_SOURCE_DECISION_POINT_INVALID",
  SOURCE_DATE_RANGE_MISMATCH: "SIGNAL_TO_PNL_SOURCE_DATE_RANGE_MISMATCH",

  // 声明校验
  COST_DECLARATION_INVALID: "SIGNAL_TO_PNL_COST_DECLARATION_INVALID",
  EXECUTION_DECLARATION_INVALID: "SIGNAL_TO_PNL_EXECUTION_DECLARATION_INVALID",

  // 编排不变量
  LOOP_PENDING_ORDER_NOT_FOUND: "SIGNAL_TO_PNL_LOOP_PENDING_NOT_FOUND",
  LOOP_CALENDAR_NOT_ASCENDING: "SIGNAL_TO_PNL_LOOP_CALENDAR_NOT_ASCENDING",
  LOOP_PRICE_SOURCE_NON_DETERMINISTIC: "SIGNAL_TO_PNL_LOOP_PRICE_SOURCE_NON_DETERMINISTIC",

  // 序列化
  RUN_INVALID: "SIGNAL_TO_PNL_RUN_INVALID",
  RUN_FINGERPRINT_MISMATCH: "SIGNAL_TO_PNL_RUN_FINGERPRINT_MISMATCH",
  SERIALIZE_NON_FINITE: "SIGNAL_TO_PNL_SERIALIZE_NON_FINITE",
} as const;

export type SignalToPnlErrorCode =
  (typeof SIGNAL_TO_PNL_ERROR_CODES)[keyof typeof SIGNAL_TO_PNL_ERROR_CODES];