/**
 * STEP 23 / C-23.1 — 模拟账户：结构化错误（FAIL FAST，稳定 code）。
 *
 * 账户状态机 / 约束检查 / 序列化在非法输入下抛 PaperAccountError（稳定 code），
 * 绝不静默 clamp / 回退 / 伪造。code 供程序化处理（非自由文本）。
 */

/** C-23.1 模拟账户错误（code 稳定）。 */
export class PaperAccountError extends Error {
  /** 稳定错误码（非自由文本）。 */
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "PaperAccountError";
    this.code = code;
  }
}

/** 稳定错误码集合（账户/订单/成交/资金/序列化）。 */
export const PAPER_ACCOUNT_ERROR_CODES = {
  // 账户构造
  ACCOUNT_INVALID: "PAPER_ACCOUNT_INVALID",
  ACCOUNT_CAPITAL_INVALID: "PAPER_ACCOUNT_CAPITAL_INVALID",
  ACCOUNT_NEGATIVE_CASH: "PAPER_ACCOUNT_NEGATIVE_CASH",
  ACCOUNT_NEGATIVE_FROZEN: "PAPER_ACCOUNT_NEGATIVE_FROZEN",
  ACCOUNT_EQUITY_MISMATCH: "PAPER_ACCOUNT_EQUITY_MISMATCH",
  ACCOUNT_ASOF_INVALID: "PAPER_ACCOUNT_ASOF_INVALID",
  ACCOUNT_POSITION_INVALID: "PAPER_ACCOUNT_POSITION_INVALID",
  ACCOUNT_FREEZE_EXCEEDS_CASH: "PAPER_ACCOUNT_FREEZE_EXCEEDS_CASH",
  ACCOUNT_UNFREEZE_EXCEEDS_FROZEN: "PAPER_ACCOUNT_UNFREEZE_EXCEEDS_FROZEN",
  ACCOUNT_AMOUNT_NONPOSITIVE: "PAPER_ACCOUNT_AMOUNT_NONPOSITIVE",

  // 订单
  ORDER_INVALID: "PAPER_ORDER_INVALID",
  ORDER_QUANTITY_NOT_LOT: "PAPER_ORDER_QUANTITY_NOT_LOT",
  ORDER_QUANTITY_NONPOSITIVE: "PAPER_ORDER_QUANTITY_NONPOSITIVE",
  ORDER_DATE_INVALID: "PAPER_ORDER_DATE_INVALID",
  ORDER_EXECUTION_BEFORE_TRADE: "PAPER_ORDER_EXECUTION_BEFORE_TRADE",
  ORDER_SIDE_INVALID: "PAPER_ORDER_SIDE_INVALID",

  // 成交
  FILL_INVALID: "PAPER_FILL_INVALID",
  FILL_QUANTITY_NOT_LOT: "PAPER_FILL_QUANTITY_NOT_LOT",
  FILL_SIDE_MISMATCH: "PAPER_FILL_SIDE_MISMATCH",

  // 约束检查（订单 → 成交）
  CHECK_LIMIT_UP: "PAPER_CHECK_LIMIT_UP",
  CHECK_LIMIT_DOWN: "PAPER_CHECK_LIMIT_DOWN",
  CHECK_INSUFFICIENT_CASH: "PAPER_CHECK_INSUFFICIENT_CASH",
  CHECK_NO_POSITION: "PAPER_CHECK_NO_POSITION",
  CHECK_INSUFFICIENT_AVAILABLE: "PAPER_CHECK_INSUFFICIENT_AVAILABLE",
  CHECK_MAX_POSITIONS_REACHED: "PAPER_CHECK_MAX_POSITIONS_REACHED",
  CHECK_PER_SECURITY_CAP_EXCEEDED: "PAPER_CHECK_PER_SECURITY_CAP_EXCEEDED",
  CHECK_TOTAL_CAP_EXCEEDED: "PAPER_CHECK_TOTAL_CAP_EXCEEDED",
  CHECK_BUY_BANNED: "PAPER_CHECK_BUY_BANNED",
  CHECK_SELL_BANNED: "PAPER_CHECK_SELL_BANNED",
  CHECK_SUSPENDED: "PAPER_CHECK_SUSPENDED",

  // 序列化
  RUN_INVALID: "PAPER_RUN_INVALID",
  RUN_FINGERPRINT_MISMATCH: "PAPER_RUN_FINGERPRINT_MISMATCH",
  SERIALIZE_NON_FINITE: "PAPER_SERIALIZE_NON_FINITE",
} as const;

export type PaperAccountErrorCode =
  (typeof PAPER_ACCOUNT_ERROR_CODES)[keyof typeof PAPER_ACCOUNT_ERROR_CODES];
